sudo: required

language: node_js

node_js:
  - "8"

dist: trusty

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run test

before_deploy:
  - ng build --prod --base-href="https://puku0x.github.io/ngx-onsenui-kitchensink/"
  - mv dist/ngx-onsenui-kitchensink/index.html dist/ngx-onsenui-kitchensink/main.html
  - cp -r static/demo dist/ngx-onsenui-kitchensink
  - cp static/demo.html dist/ngx-onsenui-kitchensink/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-onsenui-kitchensink
  on:
    branch: master
