sudo: false

language: node_js

node_js:
  - stable

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g @angular/cli

script:
  - ng test --single-run

before_deploy:
  - ng build --prod --aot --build-optimizer --base-href="https://puku0x.github.io/ngx-onsenui-kitchensink/"
  - mv dist/index.html dist/main.html
  - cp -r static/demo dist/demo
  - mv dist/demo/demo.html dist/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
